project:
  type: website
  output-dir: docs

website:
  title: "Collettivo HQ"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Chi siamo
      - href: Progetti.qmd
        text: Progetti

format:
  html:
    theme:
      - minty
      - brand
    css: styles.css
    toc: true



